repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings. 

  # The name of the repository. Changing this will rename the repository
  name: javaspringdemo2022

  # A short description of the repository that will show up on GitHub
  description: description of repo4
  
  # Either `true` to enable the wiki for this repository, `false` to disable it. 
  has_wiki: false

branches:
  - name: main
    # https://docs.github.com/en/rest/reference/repos#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      restrictions: null
      required_status_checks: null
      enforce_admins: null
      required_pull_request_reviews:
        dismissal_restrictions": {}
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        # The number of approvals required. (1-6)
        required_approving_review_count: 2
      
